//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RallyToolsCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceSafe {
            get {
                return ((string)(this["SourceSafe"]));
            }
            set {
                this["SourceSafe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSvnLogUrl {
            get {
                return ((string)(this["LastSvnLogUrl"]));
            }
            set {
                this["LastSvnLogUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NextBuildUrlTemplate {
            get {
                return ((string)(this["NextBuildUrlTemplate"]));
            }
            set {
                this["NextBuildUrlTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RallyUser {
            get {
                return ((string)(this["RallyUser"]));
            }
            set {
                this["RallyUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RallyPassword {
            get {
                return ((string)(this["RallyPassword"]));
            }
            set {
                this["RallyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RallyQuery {
            get {
                return ((string)(this["RallyQuery"]));
            }
            set {
                this["RallyQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MutedVersion {
            get {
                return ((string)(this["MutedVersion"]));
            }
            set {
                this["MutedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DailyReportTemplatePath {
            get {
                return ((string)(this["DailyReportTemplatePath"]));
            }
            set {
                this["DailyReportTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ReviewRequestTemplate {
            get {
                return ((string)(this["ReviewRequestTemplate"]));
            }
            set {
                this["ReviewRequestTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string IterationFilter {
            get {
                return ((string)(this["IterationFilter"]));
            }
            set {
                this["IterationFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideDefectSubtasks {
            get {
                return ((bool)(this["HideDefectSubtasks"]));
            }
            set {
                this["HideDefectSubtasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpgradeMarker {
            get {
                return ((int)(this["UpgradeMarker"]));
            }
            set {
                this["UpgradeMarker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideNoiseTasks {
            get {
                return ((bool)(this["HideNoiseTasks"]));
            }
            set {
                this["HideNoiseTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoiseTaskRegex {
            get {
                return ((string)(this["NoiseTaskRegex"]));
            }
            set {
                this["NoiseTaskRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateManifestUrl {
            get {
                return ((string)(this["UpdateManifestUrl"]));
            }
            set {
                this["UpdateManifestUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuildsBoardUri {
            get {
                return ((string)(this["BuildsBoardUri"]));
            }
            set {
                this["BuildsBoardUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(TrackGearLibrary.Core.MySettingProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnablePostCommitTools {
            get {
                return ((bool)(this["EnablePostCommitTools"]));
            }
            set {
                this["EnablePostCommitTools"] = value;
            }
        }
    }
}
